In [30]:
import numpy as np
a = np.array(range(30)).reshape(5, 6, order="F")
np.sort(a)

array([1, 3, 8, 9, 9, 9])

In [17]:
np.where((a % 6) == 1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))

In [31]:
#新版題目
a = np.random.randint(10, size=6) 
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
#type(a) 是顯示 a 的數列狀態；a.dtype 是回傳 a 數列中單元素型態。

type(a):  <class 'numpy.ndarray'>
a.dtype:  int32


In [36]:
b = np.random.randint(10, size=10) 
b

array([3, 1, 2, 6, 6, 7, 9, 1, 4, 5])

In [38]:
print(is_dtype(b, 'int')) 
print(is_dtype(b, np.int))
print(is_dtype(b, np.dtype('int')))

True
True
True


In [ ]:
#type()  是顯示數列的狀態，而不是元素的型態； is 相對 == 更嚴格，一定要型態正確才會回傳 True。