In [2]:
import numpy as np

V1 = 20000
V0 = 20
GdB = 20*np.log10(np.divide(V1, V0))
print('分貝數:{}'. format(GdB))

分貝數:60.0


In [3]:
GdB1 = 50
GdB2 = 30
V1 = 20 * np.power(10, np.divide(GdB1, 20))
V2 = 20 * np.power(10, np.divide(GdB2, 20))
V3 = np.divide(V2, V1)
print(V3)

0.09999999999999999


In [25]:
#新題目
#1-1
import numpy as np
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [30]:
student = np.dtype([('name','U8'), ('sex', 'U8'), ('weight', 'f4'), ('rank', 'i4'), ('myopia', '?')]) 
student_l = np.zeros(8,dtype=student)
student_l['name'] = name_list
student_l['sex'] = sex_list
student_l['weight'] = weight_list
student_l['rank'] = rank_list
student_l['myopia'] = myopia_list
student_l

array([('小明', 'boy', 67.5, 8,  True), ('小華', 'boy', 75.3, 1,  True),
       ('小菁', 'girl', 50.1, 5, False), ('小美', 'girl', 45.5, 4, False),
       ('小張', 'boy', 80.8, 7,  True), ('John', 'boy', 90.4, 6,  True),
       ('Mark', 'boy', 78.4, 2, False), ('Tom', 'boy', 70.7, 3, False)],
      dtype=[('name', '<U8'), ('sex', '<U8'), ('weight', '<f4'), ('rank', '<i4'), ('myopia', '?')])

In [32]:
#1-2
np.mean(student_l['weight'])

69.8375

In [50]:
#1-3
boy = np.where(student_l['sex']=='boy')
np.mean(student_l['weight'][boy])

77.18333

In [52]:
#1-3
girl = np.where(student_l['sex']=='girl')
np.mean(student_l['weight'][girl])

47.8

In [54]:
#2
print(np.zeros((2, 3)))#製造數值
print(np.empty((2, 3)))#製造可填入的空間

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
a = np.random.rand(3, 3)
a

array([[0.36873267, 0.76993193, 0.45834412],
       [0.15599232, 0.12727078, 0.74912907],
       [0.53617095, 0.80874438, 0.0887887 ]])

In [61]:
print(np.round(a, 0))

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [ ]:
#3
#np.reshape(np.linspace(n ,m , 9),(3, 3))