In [2]:
import numpy as np
a = np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
a[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
a[3:21:3]

array([ 3,  6,  9, 12, 15, 18])

In [33]:
e = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
              [[1, 2, 3], [4, 5, 6], [7, 8, 9]],])
print('list(e): ', list(e))
print('tolist(): ', e.tolist())
#list會有分層，tolist會列成一列

list(e):  [array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])]
tolist():  [[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]


In [36]:
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

In [37]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [38]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [40]:
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [42]:
def tolist(AA):
    if type(AA) != np.ndarray:
        return AA
    NL = []
    for A in AA:
        NL.append(tolist(A))
    return list(NL)
print(tolist(e))

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
