In [1]:
import numpy as np
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [2]:
np.sum(np.greater(english_score, math_score))

3

In [4]:
a = np.greater(chinese_score, math_score)
b = np.greater(chinese_score, english_score)
np.logical_and(a == 1, b == 1)

array([ True,  True,  True,  True,  True,  True])

In [5]:
#新題目
#1.
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

In [7]:
print(a + a)
print(a + b)
print(a + c)
print(a + d)
print(a + e)

[ 40  60  80 100]
[21 32 43 54]
[21 31 41 51]
[21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [11]:
#2.
A = np.ones(3)*1
B = np.ones(3)*2
print(A)
print(B)
print((A + B) * (-A / 2))

[1. 1. 1.]
[2. 2. 2.]
[-1.5 -1.5 -1.5]


In [10]:
#3.
A = np.ones((1,6))
B = np.ones((6,1))

print(A * B)
print(A @ B)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
