In [94]:
import numpy as np
array1 = np.array([[10, 8], [3, 5]])
array2 = np.linalg.inv(array1)
array1@array2

array([[1., 0.],
       [0., 1.]])

In [44]:
w, v = np.linalg.eig(array1)
print("特徵向量:", v)
print("特徵值:", w)

特徵向量: [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]
特徵值: [13.  2.]


In [45]:
u, s, vh = np.linalg.svd(array1)
print(u, s, vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]] [13.94721714  1.86417116] [[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]


In [46]:
#新題目
#1.
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [47]:
%timeit -n 10 a = 2

for i in Z:
    for X in i:
        for Y in X:
            i = i + 1

21.4 ns ± 8.33 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
%timeit -n 10 a = 2
for i in Z.flat:
    i = i+1

22.9 ns ± 7 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [50]:
%timeit -n 10 a = 2
for d in np.nditer(Z):
    i = i+1

22.9 ns ± 4.52 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [132]:
#2.
Z = np.random.randint(0,10,50)
print(Z)

[5 2 7 7 1 6 9 8 8 4 6 3 9 5 3 5 5 7 9 1 1 2 1 2 5 9 9 2 0 9 3 6 4 1 0 0 9
 1 3 1 5 5 8 0 3 8 3 6 8 1]


In [133]:
Z1 = np.bincount(Z)#算出次數
Z2 = Z1.argmax()#找出最多的數值
np.where(Z == Z2)#找出最多數值之位置

(array([ 4, 19, 20, 22, 33, 37, 39, 49], dtype=int64),)

In [134]:
#3
Z.tolist()

[5,
 2,
 7,
 7,
 1,
 6,
 9,
 8,
 8,
 4,
 6,
 3,
 9,
 5,
 3,
 5,
 5,
 7,
 9,
 1,
 1,
 2,
 1,
 2,
 5,
 9,
 9,
 2,
 0,
 9,
 3,
 6,
 4,
 1,
 0,
 0,
 9,
 1,
 3,
 1,
 5,
 5,
 8,
 0,
 3,
 8,
 3,
 6,
 8,
 1]

In [137]:
list(Z)

[5,
 2,
 7,
 7,
 1,
 6,
 9,
 8,
 8,
 4,
 6,
 3,
 9,
 5,
 3,
 5,
 5,
 7,
 9,
 1,
 1,
 2,
 1,
 2,
 5,
 9,
 9,
 2,
 0,
 9,
 3,
 6,
 4,
 1,
 0,
 0,
 9,
 1,
 3,
 1,
 5,
 5,
 8,
 0,
 3,
 8,
 3,
 6,
 8,
 1]