In [3]:
import numpy as np
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('homework.npz', 'wb') as f:
    np.savez(f, array1 = array1, array2 = array2)

In [4]:
array3 = np.array([[4,5,6],[1,2,3]])
homework1 = np.load('homework.npz')
with open('homework1.npz', 'wb') as f:
    np.savez(f, array1 = homework1['array1'], array2 = homework1['array2'], array3 = array3)

In [5]:
homework2 = np.load('homework1.npz')
homework2.files

['array1', 'array2', 'array3']

In [7]:
print(homework2['array1'])
print(homework2['array2'])
print(homework2['array3'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]


In [10]:
#新題目
#1.
a = np.array(range(30))
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

435
435
435


In [13]:
#2. 最小值最大值正規化(Min-Max Normalization) 為（原始資料-最小值）/（最大值-最小值）
a = np.random.random((5, 5))
a = (a - a.min()) / (a.max() - a.min())
a

array([[0.03106639, 0.60004969, 0.27814318, 0.28282427, 0.5828883 ],
       [0.15891177, 0.64092299, 0.18333685, 0.55813285, 0.75803952],
       [0.        , 0.97303201, 0.66865376, 0.8262257 , 0.57162214],
       [0.2684136 , 1.        , 0.13052982, 0.18614408, 0.2770513 ],
       [0.22892887, 0.53432584, 0.42868084, 0.31394471, 0.50955503]])

In [ ]:
a = np.random.random(10)
a[a.argmax()] = -1
print (Z)